In [11]:
import numpy as np

In [12]:
a=[[[2,3,5],[2,7,4],[8,5,3],[7,42,2]],[[2,3,5],[2,7,4],[8,5,3],[7,42,2]],[[2,3,5],[2,7,4],[8,5,3],[7,42,2]]]
a=np.array(a)

In [13]:
a=a.reshape(a.shape[0],-1)

In [14]:
a

array([[ 2,  3,  5,  2,  7,  4,  8,  5,  3,  7, 42,  2],
       [ 2,  3,  5,  2,  7,  4,  8,  5,  3,  7, 42,  2],
       [ 2,  3,  5,  2,  7,  4,  8,  5,  3,  7, 42,  2]])

In [15]:
a

array([[ 2,  3,  5,  2,  7,  4,  8,  5,  3,  7, 42,  2],
       [ 2,  3,  5,  2,  7,  4,  8,  5,  3,  7, 42,  2],
       [ 2,  3,  5,  2,  7,  4,  8,  5,  3,  7, 42,  2]])

In [16]:
a==42

array([[False, False, False, False, False, False, False, False, False,
        False,  True, False],
       [False, False, False, False, False, False, False, False, False,
        False,  True, False],
       [False, False, False, False, False, False, False, False, False,
        False,  True, False]], dtype=bool)

In [17]:
re=np.where(a==42)

In [18]:
re

(array([0, 1, 2], dtype=int64), array([10, 10, 10], dtype=int64))

In [19]:
list(range(4))

[0, 1, 2, 3]

In [20]:
a[1]

array([ 2,  3,  5,  2,  7,  4,  8,  5,  3,  7, 42,  2])

In [21]:
np.argmin(a[1])

0

In [22]:
a=np.array([[2,5,3,2],[4,2,7,8],[7,5,3,6]])

In [23]:
a

array([[2, 5, 3, 2],
       [4, 2, 7, 8],
       [7, 5, 3, 6]])

In [24]:
b=np.array([[2,5,3,7],[8,5,9,2]])

In [25]:
b

array([[2, 5, 3, 7],
       [8, 5, 9, 2]])

In [26]:
a=a[:,np.newaxis,:]
b=b[np.newaxis,:,:]

In [29]:
a-b

array([[[ 0,  0,  0, -5],
        [-6,  0, -6,  0]],

       [[ 2, -3,  4,  1],
        [-4, -3, -2,  6]],

       [[ 5,  0,  0, -1],
        [-1,  0, -6,  4]]])

In [32]:
re=np.sum(np.abs(a-b),axis=2)

In [33]:
re

array([[ 5, 12],
       [10, 15],
       [ 6, 11]])

In [ ]:
np.size(re)

In [34]:
d={'huangzp':'PB16150288','dengsl':'joajosaj'}
d['sunyk']='26945949'

In [35]:
d

{'dengsl': 'joajosaj', 'huangzp': 'PB16150288', 'sunyk': '26945949'}

In [36]:
a = [2,3,4,5]
a[1:3]

[3, 4]

In [37]:
b=['iaj','jao']
a+b

[2, 3, 4, 5, 'iaj', 'jao']