In [1]:
import numpy as np

In [2]:
a=np.random.randn(3,4)

In [7]:
a

array([[-0.10397765,  0.14000427,  0.17300343,  0.13336483],
       [ 1.35037226,  0.9139636 ,  0.45204439,  0.04877009],
       [ 0.65572262, -1.34062826, -0.36756133, -1.48323301]])

In [17]:
np.random.rand(2,3)

array([[ 0.01438399,  0.93877009,  0.99717835],
       [ 0.22467904,  0.22119396,  0.61335266]])

In [18]:
b=np.random.rand(*a.shape)<0.5

In [19]:
b

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [False,  True,  True, False]], dtype=bool)