In [1]:
import numpy as np

In [37]:
a=np.random.randn(3,4)

In [38]:
a

array([[-0.22805241,  1.90033613,  0.26574988,  1.57487222],
       [-0.5785837 , -0.23366656,  2.05175001, -1.22775544],
       [ 0.6066266 , -0.27225323,  1.26686059,  1.34851267]])

In [41]:
np.log(np.sum(np.exp(a*b),axis=1))

array([ 1.38629436,  2.24355393,  3.44618294])

In [44]:
a[range(2),(0,1)]

array([-0.22805241, -0.23366656])

In [51]:
np.zeros((4,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [58]:
np.random.choice(9,3,replace=False)

array([0, 2, 5])

In [1]:
import sys,pprint
pprint.pprint(sys.path)

['',
 'D:\\Anaconda\\python35.zip',
 'D:\\Anaconda\\DLLs',
 'D:\\Anaconda\\lib',
 'D:\\Anaconda',
 'D:\\Anaconda\\lib\\site-packages',
 'D:\\Anaconda\\lib\\site-packages\\Sphinx-1.4.6-py3.5.egg',
 'D:\\Anaconda\\lib\\site-packages\\win32',
 'D:\\Anaconda\\lib\\site-packages\\win32\\lib',
 'D:\\Anaconda\\lib\\site-packages\\Pythonwin',
 'D:\\Anaconda\\lib\\site-packages\\setuptools-27.2.0-py3.5.egg',
 'D:\\Anaconda\\lib\\site-packages\\IPython\\extensions',
 'C:\\Users\\黄志鹏\\.ipython']


In [3]:
import numpy as np
a=np.random.randn(3,4)

In [5]:
a[a>0]=1

In [6]:
a

array([[-1.73723049,  1.        ,  1.        , -1.29650919],
       [-0.83620799, -1.50191602, -0.65492363,  1.        ],
       [ 1.        ,  1.        ,  1.        , -0.63728243]])

In [9]:
np.argmax(a,axis=1)

array([1, 3, 0], dtype=int64)

In [10]:
np.linspace(40,100,7)

array([  40.,   50.,   60.,   70.,   80.,   90.,  100.])