In [1]:
import numpy as np

In [15]:
arrays=[np.random.randn(3,4) for _ in range(10)]


In [16]:
arrays

[array([[-0.0060674 ,  0.2142828 ,  0.14603379,  0.2519181 ],
        [-1.22879869,  0.60468776,  0.23378847,  0.95977917],
        [-0.94555346,  0.03491787, -1.30318045,  0.28962591]]),
 array([[-0.25518606,  1.04945543, -0.758538  , -2.0673195 ],
        [ 0.39565673, -1.03672922, -2.0182857 , -0.86065106],
        [ 1.46349322,  1.58095272,  0.76870041,  1.62659664]]),
 array([[-1.06248959,  1.21966007,  0.08610148,  0.67065207],
        [-0.35924683,  0.25878278, -1.77630507,  0.30099948],
        [-1.63241137,  0.3582119 , -0.02737052,  0.36031885]]),
 array([[-0.55311039, -0.83596708, -0.91404478,  2.03201537],
        [ 1.41913249, -1.31952637,  0.7032705 ,  1.43607818],
        [ 0.41555831,  2.49853078, -1.93468893, -1.56517699]]),
 array([[-0.38134832, -0.71891505,  1.44013478, -1.21843945],
        [-0.64082118, -1.04529031, -0.71463434,  0.35309151],
        [ 0.114429  ,  0.69991482,  0.36884088, -0.18343284]]),
 array([[ 2.62289808, -0.94612942,  0.37656215, -0.3390713 ]