In [1]:
import tensorflow as tf

In [7]:
sess = tf.InteractiveSession()

In [8]:
W=tf.Variable(tf.random_normal([3,4],stddev=1,seed=1))
x = tf. placeholder (tf.float32, shape=(None, 3), name = 'x-input')

In [9]:
print(x.name)

x-input_2:0


In [15]:
init_op=tf.global_variables_initializer()

In [16]:
sess.run(init_op)

In [17]:
print(W.eval())

[[-0.81131822  1.48459876  0.06532937 -2.4427042 ]
 [ 0.0992484   0.59122431  0.59282297 -2.12292957]
 [-0.72289723 -0.05627037  0.64354479 -0.26432407]]


In [27]:
W=tf.zeros((3,4))

In [28]:
print(sess.run(W))

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


In [29]:
W.shape

TensorShape([Dimension(3), Dimension(4)])

In [31]:
int(W.shape[0])

3

In [33]:
import numpy as np

In [34]:
np.sqrt(784)

28.0